name: PR Checks

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  static-analysis:
    name: Static Analysis
    uses: ./.github/workflows/static-analysis.yml
    with:
      go-version: '1.22'

  build:
    name: Build
    needs: static-analysis
    uses: ./.github/workflows/build.yml
    with:
      go-version: '1.22'

  unit-test:
    name: Unit Tests
    needs: build
    uses: ./.github/workflows/unit-test.yml
    with:
      go-version: '1.22'

  e2e-test:
    name: E2E Tests
    needs: unit-test
    uses: ./.github/workflows/e2e-test.yml
    with:
      go-version: '1.22'
